name: Docker
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 도커 이미지에 env 파일 포함
      - name: Create .env file
        run: |
          touch .env
          echo REACT_APP_IMPORT_IMP=${{ secrets.REACT_APP_IMPORT_IMP }}\ >> .env

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          contect: .
          file: ./Dockerfile
          push: true
          labels: latest
      - name: docker compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            docker-compose up -d
            sudo docker image prune -f
            
